spring:
  application:
    name: API
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_final
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
