version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_desafio_final
    environment:
      MYSQL_DATABASE: desafio_final
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: