version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_desafio_final
    environment:
      MYSQL_DATABASE: desafio_final
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - desafio_network

  api:
    build: .
    container_name: api_desafio_final
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/desafio_final?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    restart: unless-stopped
    networks:
      - desafio_network

volumes:
  mysql_data:

networks:
  desafio_network:
    driver: bridge